apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-config
  labels:
    app: converter
data:
  DATABASE_URL: postgres://development:development@postgresdb/markdown-api
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
