apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  namespace: md2pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: converter:latest
          # ports:
          #   - containerPort: 8000
          envFrom:
            - configMapRef:
                name: converter-config
