stages:
  - format
  - build
  # - build-image
  # - test
  # - publish

format:
  stage: format
  image: docker:24
  services:
    - docker:24-dind
  script:
    - apk add git jq curl bash just
    - curl -sL https://raw.githubusercontent.com/gabyx/githooks/main/scripts/install.sh | bash -s -- -- --use-manual
    - just format

build:
  stage: build
  image: nixpkgs/nix-flakes:nixos-22.11
  script:
    - git config --global safe.directories "*"
    - nix develop . --command just build --set parallel true
# build-image:
#   stage: build-image
#   image: docker:24
#   services:
#     - docker:24-dind
#   script:
#     - apk add git jq curl bash just
#     - just image
