edition = "2021"

fn_params_layout = "Vertical"

format_macro_matchers = true
format_strings = true

imports_granularity = "Crate"

reorder_impl_items = true
reorder_imports = true

unstable_features = true
