apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: md2pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: queue-config
            - configMapRef:
                name: api-config
