apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: md2pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: changeowner
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: blob-storage
              mountPath: /data
      containers:
        - name: api
          image: api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: queue-config
            - configMapRef:
                name: api-config
          volumeMounts:
            - mountPath: /data/blob-storage
              name: blob-storage
      securityContext:
        fsGroup: 1000
      volumes:
        - name: blob-storage
          persistentVolumeClaim:
            claimName: blob-storage-claim
