# SPDX-FileCopyrightText: © 2022 Meta Platforms, Inc. and affiliates.
# SPDX-FileCopyrightText: © 2022 Austin Seipp
# SPDX-License-Identifier: MIT OR Apache-2.0

load("@prelude-nix//basics/config.bzl", "config")

config.setting(
    name = "linux",
    constraints = [ "prelude-nix//platform/os/constraints:linux" ],
    visibility = [ "PUBLIC" ],
)

config.setting(
    name = "darwin",
    constraints = [ "prelude-nix//platform/os/constraints:darwin" ],
    visibility = [ "PUBLIC" ],
)
