allow_k8s_contexts(["default", "local-k3s"])

load("ext://dotenv", "dotenv")
env_file = os.path.join(config.main_dir, ".env")
if os.path.exists(env_file):
    direnv(fn=env_file)

# Set global parameters.
use_local_registry = os.getenv("USE_DOCKER_REGISTRY", "false") == "true"

load(
    ".tilt/Tiltfile",
    "root_dir",
    "component_dirs",
    "get_component_config",
    "get_component_path",
)

if use_local_registry:
    # Use local docker registry run in the cluster.
    default_registry("docker-registry:5000")
else:
    # Use ephemeral image registry 'ttl.sh',
    default_registry("ttl.sh/markdown-api-aksjhfkajsdf832486748237")

# Load common components.
config = get_component_config(name="common")
k8s_yaml(kustomize(config["manifest-dir"]))

# Load all other components.
for p in component_dirs:
    f = os.path.join(p, "Tiltfile")
    if os.path.exists(f):
        load_dynamic(f)

# All other needed stuff such as database and the rabbitmq queue.
config = get_component_config(name="rabbitmq")
k8s_yaml(kustomize(config["manifest-dir"]))
k8s_resource(workload=config["name"], port_forwards=15672)

config = get_component_config(name="mongodb")
k8s_yaml(kustomize(config["manifest-dir"]))
k8s_resource(workload=config["name"], port_forwards=27017)

config = get_component_config(name="postgresdb")
k8s_yaml(kustomize(config["manifest-dir"]))
k8s_resource(workload=config["name"], port_forwards=5432)
