allow_k8s_contexts(["default", "local-k3s"])

load(
    "common/Tiltfile",
    "root_dir",
    "component_dirs",
    "get_component_config",
    "get_component_path",
)

use_local_registry = False
if use_local_registry:
    # Use local docker registry run in the cluster.
    default_registry("docker-registry:5000")
else:
    # Use ephemeral image registry 'ttl.sh',
    default_registry("ttl.sh/markdown-api-aksjhfkajsdf832486748237")

# Load all components.
for p in component_dirs:
    f = os.path.join(p, "Tiltfile")
    if os.path.exists(f):
        load_dynamic(f)

# All other needed stuff such as database and the rabbitmq queue.
config = get_component_config(name='rabbitmq')
print(config)
k8s_yaml(kustomize(config["manifest-dir"]))
k8s_resource(workload=config["name"], port_forwards=15672)

config = get_component_config(name='mongodb')
print(config)
k8s_yaml(kustomize(config["manifest-dir"]))
k8s_resource(workload=config["name"], port_forwards=27017)

config = get_component_config('postgresdb')
k8s_yaml(kustomize(config["manifest-dir"]))
k8s_resource(workload=config["name"], port_forwards=5432)
