root_dir := justfile_directory()

build:
    cd "{{root_dir}}" && cargo build

watch:
    cd "{{root_dir}}" && cargo watch -x 'run'

format:
    cd "{{root_dir}}" && \
    	docker run -v "$(pwd):/workspace" -w "/workspace" \
    	instrumentisto/rust:nightly-alpine cargo fmt
