set positional-arguments
set fallback := true
set shell := ["bash", "-cue"]

comp_dir := justfile_directory()
root_dir := `git rev-parse --show-toplevel`

build *args:
    cd "{{comp_dir}}" && cargo build "${@:1}"

build-image *args:
    @echo "Nothing to build for this component"

watch:
    cd "{{comp_dir}}" && cargo watch -x 'build'

format:
    source "{{root_dir}}/tools/general.sh" && \
        cd "{{comp_dir}}" && \
    	ci_container_mgr_run_mounted "$(pwd)" \
    	docker.io/instrumentisto/rust:alpine \
    	cargo fmt -- --config-path /repo

lint *args:
    source "{{root_dir}}/tools/general.sh" && \
        cd "{{comp_dir}}" && \
    	ci_container_mgr_run_mounted "$(pwd)" \
    	    docker.io/gabyxgabyx/rsmd2pdf-service:ci-lint-2.0.0 \
            /repo/tools/run-rust-lint.sh {{args}}
