set positional-arguments
set shell := ["bash", "-cue"]
comp_dir := justfile_directory()
root_dir := `git rev-parse --show-toplevel`

build *args:
    cd "{{comp_dir}}" && cargo build "${@:1}"

build-image *args:
    docker build --progress plain "${@:1}" -t "md2pdf-converter-service:test" -f docker/Dockerfile "{{root_dir}}"

watch:
    cd "{{comp_dir}}" && cargo watch -x 'build'

format:
    cd "{{comp_dir}}" && \
    	docker run -v "{{root_dir}}:/repo" -v "$(pwd):/workspace" -w "/workspace" \
    	instrumentisto/rust:nightly-alpine cargo fmt -- --config-path /repo
