set positional-arguments
set fallback := true
set shell := ["bash", "-cue"]

comp_dir := justfile_directory()
root_dir := `git rev-parse --show-toplevel`

build *args:
    cd "{{comp_dir}}" && cargo build "${@:1}"

build-image *args:
    # docker build --progress plain "${@:1}" -t "md2pdf-api-service:test" -f docker/service/Dockerfile "{{root_dir}}"
    cd "{{comp_dir}}" && docker build --progress plain "${@:1}" -t "md2pdf-api-db-migration:test" -f docker/db-migration/Dockerfile "{{root_dir}}"

watch:
    cd "{{comp_dir}}" && cargo watch -x 'build'

db-migration:
    cd "{{comp_dir}}" && \
        source .env && \
        diesel migration run --config-file diesel.toml

db-migration-redo:
    cd "{{comp_dir}}" && \
        source .env && \
        diesel migration redo --all --config-file diesel.toml

format:
    source "{{root_dir}}/tools/general.sh" && \
        cd "{{comp_dir}}" && \
    	ci_container_mgr_run_mounted "$(pwd)" \
    	docker.io/instrumentisto/rust:nightly-alpine \
    	sh -c "rustup component add rustfmt; cargo fmt -- --config-path /repo"

lint *args:
    cd "{{comp_dir}}" && \
        {{root_dir}}/tools/run-rust-lint.sh {{args}}
