stages:
  - lint
  - format
  - build
  - package

.default_dind_service: &default-dind-service
  - name: gabyxgabyx/rsmd2pdf-service:ci-docker-dind-1.0.0
    alias: docker

.defaults-rules: &defaults-rules
  - if: "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature|bugfix/ ||
      $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    when: always

.main-rules: &main-rules
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    when: always

# upload-ci-images:
#   stage: package
#   needs: []
#   image: gabyxgabyx/rsmd2pdf-service:ci-docker-1.0.0
#   rules:
#     - *main-rules
#   services: *default-dind-service
#   script:
#     - apk add git bash just findutils parallel
#     - just upload-ci-images

lint:
  stage: lint
  needs: []
  image: gabyxgabyx/rsmd2pdf-service:ci-lint-2.0.1
  rules:
    - *defaults-rules
  script:
    - source .gitlab/scripts/before-script.sh
    - nix develop .#ci --command
      just --set parallel true lint
#
lint-docs:
  stage: lint
  needs: []
  image: gabyxgabyx/rsmd2pdf-service:ci-lint-2.0.1
  rules:
    - *defaults-rules
  script:
    - source .gitlab/scripts/before-script.sh
    - nix develop .#ci --command
      just --set parallel true lint-docs
  allow_failure: true

build:
  stage: build
  needs: []
  image: gabyxgabyx/rsmd2pdf-service:ci-build-2.0.1
  rules:
    - *defaults-rules
  script:
    - source .gitlab/scripts/before-script.sh
    - nix develop .#ci --command
      just --set parallel true build

format:
  stage: format
  needs: []
  image: gabyxgabyx/rsmd2pdf-service:ci-format-2.0.1
  rules:
    - *defaults-rules
  script:
    - source .gitlab/scripts/before-script.sh
    - nix develop .#ci --command
      just --set parallel true format
