apiVersion: v1
kind: ConfigMap
metadata:
  name: queue-config
  namespace: md2pdf
data:
  RABBITMQ_HOST: rabbitmq.md2pdf
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest

  QUEUE_JOBS: md2pdf.jobs
  QUEUE_JOBS_DURABLE: "false"
  QUEUE_JOBS_ROUTING_KEY: md2pdf.job

  QUEUE_STATUS: md2pdf.status
  QUEUE_STATUS_DURABLE: "false"
  QUEUE_STATUS_ROUTING_KEY: md2pdf.status

  EXCHANGE_NAME: md2pdf.exchange
