load("@prelude//toolchains/rust/main.bzl", "rust")

rust.binary(
    name = "web-service",
    file = "main.rs",
    out = "web-service",
    # deps = [
    #     # "//components/web/third-party:dotenv",
    # ],
)
